#ifndef RECURSION_ENGINE__SRC__CORE__EVENTS__MOUSE_MAPPING_HH
#define RECURSION_ENGINE__SRC__CORE__EVENTS__MOUSE_MAPPING_HH

/*
    copied from https://www.glfw.org/docs/3.3/group__keys.html
*/

#define REC_MOUSE_BUTTON_1 0
#define REC_MOUSE_BUTTON_2 1
#define REC_MOUSE_BUTTON_3 2
#define REC_MOUSE_BUTTON_4 3
#define REC_MOUSE_BUTTON_5 4
#define REC_MOUSE_BUTTON_6 5
#define REC_MOUSE_BUTTON_7 6
#define REC_MOUSE_BUTTON_8 7
#define REC_MOUSE_BUTTON_LAST REC_MOUSE_BUTTON_8
#define REC_MOUSE_BUTTON_LEFT REC_MOUSE_BUTTON_1
#define REC_MOUSE_BUTTON_RIGHT REC_MOUSE_BUTTON_2
#define REC_MOUSE_BUTTON_MIDDLE REC_MOUSE_BUTTON_3

#endif