#ifndef RECURSION_ENGINE__SRC__CORE__WINDOW__WINDOW_CONFIG_HH
#define RECURSION_ENGINE__SRC__CORE__WINDOW__WINDOW_CONFIG_HH

#define CONF__REC__WINDOW_POSX 0
#define CONF__REC__WINDOW_POSY 0

#define CONF__REC__WINDOW_WIDTH 2560.0
#define CONF__REC__WINDOW_HEIGHT 1440.0

#endif